# db url: 172.17.0.2
version: '3.3'
services:
  nest-postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=0CZ1kn39zHuzvg@2
    depends_on:
      - admin-nest-postgres

  admin-nest-postgres:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=diegohdez12@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=jKPzqTc4C94nLMviU

networks:
  nest-network: